### ISSUE TITLE
Error while Running the container

### ISSUE THREAD

**Issue by Sainith123** [piyushgarg-dev/vercel-clone#10]
E:\vercel-clone\build-server>docker run -it -p 8080:5000 myvercel
exec /home/app/main.sh: no such file or directory

**Comment by Sainith123** [comment]
getting this even after rebuilding many times(cache disabled)

**Comment by coderboy-yash** [comment]
> getting this even after rebuilding many times(cache disabled)

I AM Getting the same error , did you find a way to resolve it ?

**Comment by ishanaudichya** [comment]
This is the same issue as #6. The issue of end-of-line chars. Check out the issue #6. Lmk if the error persists

**Comment by Sainith123** [comment]
@ishanaudichya thank you. the error got resolved
