### ISSUE TITLE
How to setup Custom Domain and I wish to expose port

### ISSUE THREAD

**Issue by loyality7** [piyushgarg-dev/vercel-clone#16]
I want to deploy project with custom domain if user doesn't have own domain can use my *.example.com if he has a Domain How to Connect it and i don't want show user to port

**Comment by akram6t** [comment]
You need to add a CNAME or A record for the custom domain in the DNS settings, pointing to the domain/IP of your S3 proxy server (which will be hosted on example.com). Whenever a request comes to the custom domain, it will hit the S3 proxy server. On the server, you can perform domain resolution and query the database to find the projectId associated with the domain. Then, you can run the project based on the fetched projectId.

**Comment by loyality7** [comment]
Cool , Thank you boss
