### ISSUE TITLE
Getting Error when run task 

### ISSUE THREAD

**Issue by Ankit-Yadav-21** [piyushgarg-dev/vercel-clone#6]
![Screenshot 2024-02-13 112836](https://github.com/piyushgarg-dev/vercel-clone/assets/110392565/15dc483f-187a-4b49-aaf5-fd6d7a4ea8fb)

run same code but when i run task on cluster get this.

@piyushgarg-dev kindly check once 

![image](https://github.com/piyushgarg-dev/vercel-clone/assets/110392565/ec2a65f9-dce8-4fb5-ba94-d4e31c5eb91c)
 
this is same docker file

**Comment by piyushgarg-dev** [comment]
Try Rebuilding the Docker Image and pushing back and re-run.

**Comment by Sainith123** [comment]
@Ankit-Yadav-21 did your error got resolved? even I am getting same

**Comment by Ankit-Yadav-21** [comment]
> @Ankit-Yadav-21 did your error got resolved? even I am getting same

@Sainith123 still facing same error

**Comment by Ankit-Yadav-21** [comment]
> Try Rebuilding the Docker Image and pushing back and re-run.

Bro I try many time but still not resolved

**Comment by vaibhavyadav-dev** [comment]
> > Try Rebuilding the Docker Image and pushing back and re-run.
> 
> Bro I try many time but still not resolved



> ![Screenshot 2024-02-13 112836](https://private-user-images.githubusercontent.com/110392565/304308808-15dc483f-187a-4b49-aaf5-fd6d7a4ea8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzI2OTcsIm5iZiI6MTcwNzgzMjM5NywicGF0aCI6Ii8xMTAzOTI1NjUvMzA0MzA4ODA4LTE1ZGM0ODNmLTE4N2EtNGI0OS1hYWY1LWZkNmQ3YTRlYThmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMzUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmE1ZjMwYThiYjE5NDhhZjZkMDBjZjUxNzU0ZmRmMWRhMWJjNTBiNzE2ODE5NDFiYmNkNjMxYTc3YjUzN2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xbt3LqW3XTkLYesrV7QWV2FD-hx6gc4QPTuAY84jiNo)
> 
> run same code but when i run task on cluster get this.
> 
> @piyushgarg-dev kindly check once
> 
> ![image](https://private-user-images.githubusercontent.com/110392565/304309445-ec2a65f9-dce8-4fb5-ba94-d4e31c5eb91c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzI2OTcsIm5iZiI6MTcwNzgzMjM5NywicGF0aCI6Ii8xMTAzOTI1NjUvMzA0MzA5NDQ1LWVjMmE2NWY5LWRjZTgtNGZiNS1iYTk0LWQ0ZTMxYzVlYjkxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMzUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzJhYTJkM2JlYTE4ZjBkZTcwM2EzMTFkMjQ4NTlmYzg0Y2NmYzVlMzViOTg3M2NiNTIzNzRhY2I4NGUzN2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WgjNtClTDLexQJMp3ge_dJr6f1ys4B_9BODP2Uj37aw)
> 
> this is same docker file


Iooks like it can not find main.sh file in the present directory, try to run locally and check, probably you are using old image again and again.

**Comment by Sainith123** [comment]
@CaptainTron  if we inspect the directories in the container using docker desktop we are able to find the file. but if we try to run the container, getting that file not found error.

@piyushgarg-dev plz help.

**Comment by Ankit-Yadav-21** [comment]
> @CaptainTron if we inspect the directories in the container using docker desktop we are able to find the file. but if we try to run the container, getting that file not found error.
> 
> @piyushgarg-dev plz help.

**EXACT SAME** for me

**Comment by ishanaudichya** [comment]
You might be building it using an x86 machine running docker and pushing it to AWS ECR with an arm64 architecture. 
Instead while building using docker use docker buildx command and specify to use platform linux/arm64

Use this command 
`docker buildx build --platform linux/arm64 -t vercel-builder-service .`
_replace image with your image name_
Also piyush used arm64 so its easy to follow up.
Let me know if the issue is fixed.

**Comment by Ankit-Yadav-21** [comment]
> You might be building it using an x86 machine running docker and pushing it to AWS ECR with an arm64 architecture. Instead while building using docker use docker buildx command and specify to use platform linux/arm64
> 
> Use this command `docker buildx build --platform linux/arm64 -t vercel-builder-service .` _replace image with your image name_ Also piyush used arm64 so its easy to follow up. Let me know if the issue is fixed.

![Screenshot 2024-02-19 180140](https://github.com/piyushgarg-dev/vercel-clone/assets/110392565/8d8eed69-8c65-4156-961b-8424c1810cfd)


Still same (I use command that you give - 'docker buildx build --platform linux/arm64 -t vercel-builder-service .' )

**Comment by ishanaudichya** [comment]
> > You might be building it using an x86 machine running docker and pushing it to AWS ECR with an arm64 architecture. Instead while building using docker use docker buildx command and specify to use platform linux/arm64
> > 
> > Use this command `docker buildx build --platform linux/arm64 -t vercel-builder-service .` _replace image with your image name_ Also piyush used arm64 so its easy to follow up. Let me know if the issue is fixed.
> 
> ![Screenshot 2024-02-19 180140](https://github.com/piyushgarg-dev/vercel-clone/assets/110392565/8d8eed69-8c65-4156-961b-8424c1810cfd)
> 
> 
> Still same (I use command that you give - 'docker buildx build --platform linux/arm64 -t vercel-builder-service .' )  

Hey ankit. I was facing the same issue with same error as main.sh file not found. I cannot work on without more details. I ll suggest u to check these conditions which might be wrong. 
- Check the task definations and make sure you have selected linux/arm64
- Check if the dockerfile has workdir set properly and the main.sh file is included in the docker image .

If u still face an issue u can check out my own repository which has the buil_server code that works for sure.
Glad i could help

**Comment by piyushgarg-dev** [comment]
Hi Everyone, 
The issue is that I used linux/arm64 in the video, If you are on windows and using Intel based CPU you should choose x86_64 option from the dropdown under Task Defination.

**Comment by ishanaudichya** [comment]
Hey, sorry for the delay. I was just able to reproduce the bug and did some research. 

Turns out that when making the main.sh file in windows it creates a CRLF line ending file. Linux uses LF, so to convert it just open the file up in vscode (or any IDE)  and rightclick the bottom right where you see windows CRLF and swap it to Linux LF
![image](https://github.com/piyushgarg-dev/vercel-clone/assets/93155612/075ec5f1-641a-4bfa-af72-fb85bfa922b9)
This is in CRLF... Convert this to LF
![image](https://github.com/piyushgarg-dev/vercel-clone/assets/93155612/ee5c2684-f523-4028-af7a-168c08eb49d9)
I am pretty sure the issue is now resolved.(Damn Sure)
@piyushgarg-dev

**Comment by ishanaudichya** [comment]
Devs please review this end i think this issue is closed. Thanks

**Comment by coderboy-yash** [comment]
> Hey, sorry for the delay. I was just able to reproduce the bug and did some research.
> 
> Turns out that when making the main.sh file in windows it creates a CRLF line ending file. Linux uses LF, so to convert it just open the file up in vscode (or any IDE) and rightclick the bottom right where you see windows CRLF and swap it to Linux LF ![image](https://private-user-images.githubusercontent.com/93155612/308500483-075ec5f1-641a-4bfa-af72-fb85bfa922b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTQyNTksIm5iZiI6MTcwOTk5Mzk1OSwicGF0aCI6Ii85MzE1NTYxMi8zMDg1MDA0ODMtMDc1ZWM1ZjEtNjQxYS00YmZhLWFmNzItZmI4NWJmYTkyMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MGY5MzhiOWYxM2ZkYjFkMGExNDFhN2EwY2RiM2NjMDI1ZmFmOWU5MGE3NjAwZmFkZTRmZmI3NGI4Y2VmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xf7QsccHLsAcUvFMKwahzY_rBgbqGouD4wHm-XHC5Y) This is in CRLF... Convert this to LF ![image](https://private-user-images.githubusercontent.com/93155612/308500790-ee5c2684-f523-4028-af7a-168c08eb49d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTQyNTksIm5iZiI6MTcwOTk5Mzk1OSwicGF0aCI6Ii85MzE1NTYxMi8zMDg1MDA3OTAtZWU1YzI2ODQtZjUyMy00MDI4LWFmN2EtMTY4YzA4ZWI0OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODk5N2IzYzg0ZTA4NzM3ZjZmMTVkYTBlZTYxMDE2YjBlNDZlY2I3MDg5MzM3OGE2YWFhNzJiNTk0YWZmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PfjTbWUJKR-TE98HkXug9d_fBndrc-NaM_ZZr1FUO8I) I am pretty sure the issue is now resolved.(Damn Sure) @piyushgarg-dev

HEADS OFF TO YOU BRO , SOLVED THE ISSUE.
